package com.sahilrawat.DelhiMetro.service;

import com.sahilrawat.DelhiMetro.model.Station;
import org.checkerframework.checker.units.qual.A;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.ArrayList;
import java.util.List;

public class GetAllStations {
    public static ArrayList<Station> stations = new ArrayList<>(List.of(
            new Station(1, "Shaheed Sthal(New Bus Adda)", "Red"),
            new Station(2, "Hindon River", "Red"),
            new Station(3, "Arthala", "Red"),
            new Station(4, "Mohan Nagar", "Red"),
            new Station(5, "Shyam park", "Red"),
            new Station(6, "Major Mohit Sharma", "Red"),
            new Station(7, "Raj Bagh", "Red"),
            new Station(8, "Shaheed Nagar", "Red"),
            new Station(9, "Dilshad Garden", "Red"),
            new Station(10, "Jhil Mil", "Red"),
            new Station(11, "Mansarovar Park", "Red"),
            new Station(12, "Shahdara", "Red"),
            new Station(13, "Welcome", "Red"),
            new Station(14, "Seelampur", "Red"),
            new Station(15, "Shastri Park", "Red"),
            new Station(16, "Kashmere Gate", "Red"),
            new Station(17, "Tis Hazari", "Red"),
            new Station(18, "Pul Bangash", "Red"),
            new Station(19, "Pratap Nagar", "Red"),
            new Station(20, "Shastri Nagar", "Red"),
            new Station(21, "Inderlok", "Red"),
            new Station(22, "Kanhaiya Nagar", "Red"),
            new Station(23, "Keshav Puram", "Red"),
            new Station(24, "Netaji Subash Place", "Red"),
            new Station(25, "Kohat Enclave", "Red"),
            new Station(26, "Pitam Pura", "Red"),
            new Station(27, "Rohini East", "Red"),
            new Station(28, "Rohini West", "Red"),
            new Station(29, "Rithala", "Red"),
            new Station(30, "Samaypur Badli", "Yellow"),
            new Station(31, "Rohini Sector 18-19", "Yellow"),
            new Station(32, "Haiderpur Badli Mor", "Yellow"),
            new Station(33, "Jahangirpuri", "Yellow"),
            new Station(34, "Adarsh Nagar", "Yellow"),
            new Station(35, "Azadpur", "Yellow"),
            new Station(36, "Model Town", "Yellow"),
            new Station(37, "Guru Tegh Bahadur Nagar", "Yellow"),
            new Station(38, "Vishwavidyalaya", "Yellow"),
            new Station(39, "Vidhan Sabha", "Yellow"),
            new Station(40, "Civil Lines", "Yellow"),
            new Station(41, "Kashmere Gate", "Yellow"),
            new Station(42, "Chandni Chowk", "Yellow"),
            new Station(43, "Chawri Bazar", "Yellow"),
            new Station(44, "New Delhi", "Yellow"),
            new Station(45, "Rajiv Chowk", "Yellow"),
            new Station(46, "Patel Chowk", "Yellow"),
            new Station(47, "Central Secretariat", "Yellow"),
            new Station(48, "Udyog Bhawan", "Yellow"),
            new Station(49, "Lok Kalyan Marg", "Yellow"),
            new Station(50, "Jorbagh", "Yellow"),
            new Station(51, "Dilli Haat INA", "Yellow"),
            new Station(52, "AIIMS", "Yellow"),
            new Station(53, "Green Park", "Yellow"),
            new Station(54, "Hauz Khas", "Yellow"),
            new Station(55, "Malviya Nagar", "Yellow"),
            new Station(56, "Saket", "Yellow"),
            new Station(57, "Qutab Minar", "Yellow"),
            new Station(58, "Chhattarpur", "Yellow"),
            new Station(59, "Sultanpur", "Yellow"),
            new Station(60, "Ghitorni", "Yellow"),
            new Station(61, "Arjan Garh", "Yellow"),
            new Station(62, "Guru Dronacharya", "Yellow"),
            new Station(63, "Sikandarpur", "Yellow"),
            new Station(64, "MG Road", "Yellow"),
            new Station(65, "IFFCO Chowk", "Yellow"),
            new Station(66, "Huda City Centre", "Yellow"),
            new Station(67, "Dwarka Sector 21", "Blue"),
            new Station(68, "Dwarka Sector 8", "Blue"),
            new Station(69, "Dwarka Sector 9", "Blue"),
            new Station(70, "Dwarka Sector 10", "Blue"),
            new Station(71, "Dwarka Sector 11", "Blue"),
            new Station(72, "Dwarka Sector 12", "Blue"),
            new Station(73, "Dwarka Sector 13", "Blue"),
            new Station(74, "Dwarka Sector 14", "Blue"),
            new Station(75, "Dwarka", "Blue"),
            new Station(76, "Dwarka Mor", "Blue"),
            new Station(77, "Nawada", "Blue"),
            new Station(78, "Uttam Nagar West", "Blue"),
            new Station(79, "Uttam Nagar East", "Blue"),
            new Station(80, "Janak Puri West", "Blue"),
            new Station(81, "Janak Puri East", "Blue"),
            new Station(82, "Tilak Nagar", "Blue"),
            new Station(83, "Subhash Nagar", "Blue"),
            new Station(84, "Tagore Garden", "Blue"),
            new Station(85, "Rajouri Garden", "Blue"),
            new Station(86, "Ramesh Nagar", "Blue"),
            new Station(87, "Moti Nagar", "Blue"),
            new Station(88, "Kirti Nagar", "Blue"),
            new Station(89, "Shadipur", "Blue"),
            new Station(90, "Patel Nagar", "Blue"),
            new Station(91, "Rajendra Place", "Blue"),
            new Station(92, "Karol Bagh", "Blue"),
            new Station(93, "Jhandewalan", "Blue"),
            new Station(94, "R K Ashram Marg", "Blue"),
            new Station(95, "Rajiv Chowk", "Blue"),
            new Station(96, "Barakhamba", "Blue"),
            new Station(97, "Mandi House", "Blue"),
            new Station(98, "Supreme Court (Pragati Maidan)", "Blue"),
            new Station(99, "Indraprastha", "Blue"),
            new Station(100, "Yamuna Bank", "Blue"),
            new Station(101, "Akshardham", "Blue"),
            new Station(102, "Mayur Vihar Phase-1", "Blue"),
            new Station(103, "Mayur Vihar Extention", "Blue"),
            new Station(104, "New Ashok Nagar", "Blue"),
            new Station(105, "Noida Sector 15", "Blue"),
            new Station(106, "Noida Sector 16", "Blue"),
            new Station(107, "Noida Sector 18", "Blue"),
            new Station(108, "Botanical Garden", "Blue"),
            new Station(109, "Golf Course", "Blue"),
            new Station(110, "Noida City Center", "Blue"),
            new Station(111, "Noida Sector 34", "Blue"),
            new Station(112, "Noida Sector 52", "Blue"),
            new Station(113, "Noida Sector 61", "Blue"),
            new Station(114, "Noida Sector 59", "Blue"),
            new Station(115, "Noida Sector 62", "Blue"),
            new Station(116, "Noida Electronic City", "Blue"),
            new Station(117, "New Delhi-Airport Express", "AirportExpress"),
            new Station(118, "Shivaji Stadium", "AirportExpress"),
            new Station(119, "Dhaula Kuan", "AirportExpress"),
            new Station(120, "Delhi Aerocity", "AirportExpress"),
            new Station(121, "IGI Airport", "AirportExpress"),
            new Station(122, "Dwarka Sector 21", "AirportExpress"),
            new Station(123, "Inderlok", "GreenLine-IndrloktoMundka"),
            new Station(124, "Ashok Park Main", "GreenLine-IndrloktoMundka"),
            new Station(125, "Punjabi Bagh", "GreenLine-IndrloktoMundka"),
            new Station(126, "Shivaji Park", "GreenLine-IndrloktoMundka"),
            new Station(127, "Madipur", "GreenLine-IndrloktoMundka"),
            new Station(128, "Paschim Vihar (East)", "GreenLine-IndrloktoMundka"),
            new Station(129, "Paschim Vihar (West)", "GreenLine-IndrloktoMundka"),
            new Station(130, "Peera Garhi", "GreenLine-IndrloktoMundka"),
            new Station(131, "Udyog Nagar", "GreenLine-IndrloktoMundka"),
            new Station(132, "Maharaja Surajmal Stadium", "GreenLine-IndrloktoMundka"),
            new Station(133, "Nangloi", "GreenLine-IndrloktoMundka"),
            new Station(134, "Nangloi Railway Station", "GreenLine-IndrloktoMundka"),
            new Station(135, "Rajdhani Park", "GreenLine-IndrloktoMundka"),
            new Station(136, "Mundka", "GreenLine-IndrloktoMundka"),
            new Station(137, "Mundka Industrial Area (MIA)", "GreenLine-IndrloktoMundka"),
            new Station(138, "Ghevra Metro station", "GreenLine-IndrloktoMundka"),
            new Station(139, "Tikri Kalan", "GreenLine-IndrloktoMundka"),
            new Station(140, "Tikri Border", "GreenLine-IndrloktoMundka"),
            new Station(141, "Pandit Shree Ram Sharma", "GreenLine-IndrloktoMundka"),
            new Station(142, "Bahdurgarh City", "GreenLine-IndrloktoMundka"),
            new Station(143, "Brigadier Hoshiar Singh", "GreenLine-IndrloktoMundka"),
            new Station(144, "Sector 55-66 (Rapid Metro)", "Rapid"),
            new Station(145, "Sector 54 Chowk (Rapid Metro)", "Rapid"),
            new Station(146, "Sector 53-54 (Rapid Metro)", "Rapid"),
            new Station(147, "Sector 42-43 (Rapid Metro)", "Rapid"),
            new Station(148, "DLF Phase 1 (Rapid Metro)", "Rapid"),
            new Station(149, "Sikandarpur (Rapid Metro)", "Rapid"),
            new Station(150, "DLF Phase 2 (Rapid Metro)", "Rapid"),
            new Station(151, "Belvedere Towers (Rapid Metro)", "Rapid"),
            new Station(152, "Cyber City (Rapid Metro)", "Rapid"),
            new Station(153, "Moulsari Avenue (Rapid Metro)", "Rapid"),
            new Station(154, "DLF Phase 3 (Rapid Metro)", "Rapid"),
            new Station(155, "Kashmere Gate", "Violet"),
            new Station(156, "Lal Quila", "Violet"),
            new Station(157, "Jama Masjid", "Violet"),
            new Station(158, "Delhi Gate", "Violet"),
            new Station(159, "ITO", "Violet"),
            new Station(160, "Mandi House", "Violet"),
            new Station(161, "Janpath", "Violet"),
            new Station(162, "Central Secretariat", "Violet"),
            new Station(163, "Khan Market", "Violet"),
            new Station(164, "Jawaharlal Nehru Stadium", "Violet"),
            new Station(165, "Jangpura", "Violet"),
            new Station(166, "Lajpat Nagar", "Violet"),
            new Station(167, "Moolchand", "Violet"),
            new Station(168, "Kailash Colony", "Violet"),
            new Station(169, "Nehru Place", "Violet"),
            new Station(170, "Kalkaji Mandir", "Violet"),
            new Station(171, "Govind Puri", "Violet"),
            new Station(172, "Okhla", "Violet"),
            new Station(173, "Jasola", "Violet"),
            new Station(174, "Sarita Vihar", "Violet"),
            new Station(175, "Mohan Estate", "Violet"),
            new Station(176, "Tughlakabad", "Violet"),
            new Station(177, "Badarpur Border", "Violet"),
            new Station(178, "Sarai", "Violet"),
            new Station(179, "N.H.P.C. Chowk", "Violet"),
            new Station(180, "Mewala Maharajpur", "Violet"),
            new Station(181, "Sector 28 Faridabad", "Violet"),
            new Station(182, "Badkal Mor", "Violet"),
            new Station(183, "Old Faridabad", "Violet"),
            new Station(184, "Neelam Chowk Ajronda", "Violet"),
            new Station(185, "Bata Chowk", "Violet"),
            new Station(186, "Escorts Mujesar", "Violet"),
            new Station(187, "Sant Surdas - Sihi", "Violet"),
            new Station(188, "Raja Nahar Singh", "Violet"),
            new Station(189, "Janak Puri West", "Magenta"),
            new Station(190, "Dabri Mor - Janakpuri South", "Magenta"),
            new Station(191, "Dashrath Puri", "Magenta"),
            new Station(192, "Palam", "Magenta"),
            new Station(193, "Sadar Bazaar Cantonment", "Magenta"),
            new Station(194, "Terminal 1 IGI Airport", "Magenta"),
            new Station(195, "Shankar Vihar", "Magenta"),
            new Station(196, "Vasant Vihar", "Magenta"),
            new Station(197, "Munirka", "Magenta"),
            new Station(198, "RK Puram", "Magenta"),
            new Station(199, "IIT Delhi", "Magenta"),
            new Station(200, "Hauz Khas", "Magenta"),
            new Station(201, "Panchsheel Park", "Magenta"),
            new Station(202, "Chirag Delhi", "Magenta"),
            new Station(203, "Greater Kailash", "Magenta"),
            new Station(204, "Nehru Enclave", "Magenta"),
            new Station(205, "Kalkaji Mandir", "Magenta"),
            new Station(206, "Okhla NSIC", "Magenta"),
            new Station(207, "Sukhdev Vihar", "Magenta"),
            new Station(208, "JAMIA MILLIA ISLAMIA", "Magenta"),
            new Station(209, "Okhla Vihar", "Magenta"),
            new Station(210, "Jasola Vihar Shaheen Bagh", "Magenta"),
            new Station(211, "Kalindi Kunj", "Magenta"),
            new Station(212, "Okhla Bird Sanctuary", "Magenta"),
            new Station(213, "Botanical Garden", "Magenta"),
            new Station(214, "Majlis Park", "Pink"),
            new Station(215, "Azadpur", "Pink"),
            new Station(216, "Shalimar Bagh", "Pink"),
            new Station(217, "Netaji Subash Place", "Pink"),
            new Station(218, "Shakurpur", "Pink"),
            new Station(219, "Punjabi Bagh West", "Pink"),
            new Station(220, "ESI BASAI DARAPUR", "Pink"),
            new Station(221, "Rajouri Garden", "Pink"),
            new Station(222, "Maya Puri", "Pink"),
            new Station(223, "Naraina Vihar", "Pink"),
            new Station(224, "Delhi Cantt", "Pink"),
            new Station(225, "Durgabai Deshmukh South Campus", "Pink"),
            new Station(226, "Sir Vishweshwaraiah Moti Bagh", "Pink"),
            new Station(227, "Bhikaji Cama Place", "Pink"),
            new Station(228, "Sarojini Nagar", "Pink"),
            new Station(229, "Dilli Haat INA", "Pink"),
            new Station(230, "South Extension", "Pink"),
            new Station(231, "Lajpat Nagar", "Pink"),
            new Station(232, "Vinobapuri", "Pink"),
            new Station(233, "Ashram", "Pink"),
            new Station(234, "Sarai Kale Khan Hazrat Nizamuddin", "Pink"),
            new Station(235, "Mayur Vihar Phase-1", "Pink"),
            new Station(236, "Mayur Vihar Pocket I", "Pink"),
            new Station(237, "Trilokpuri Sanjay Lake", "Pink"),
            new Station(238, "Vinod Nagar East", "Pink"),
            new Station(239, "Mandawali - West Vinod Nagar", "Pink"),
            new Station(240, "IP Extension", "Pink"),
            new Station(241, "Anand Vihar", "Pink"),
            new Station(242, "Karkar Duma", "Pink"),
            new Station(243, "Karkarduma Court", "Pink"),
            new Station(244, "Krishna Nagar", "Pink"),
            new Station(245, "East Azad Nagar", "Pink"),
            new Station(246, "Welcome", "Pink"),
            new Station(247, "Jaffrabad", "Pink"),
            new Station(248, "Maujpur", "Pink"),
            new Station(249, "Gokulpuri", "Pink"),
            new Station(250, "Johri Enclave", "Pink"),
            new Station(251, "Shiv Vihar", "Pink"),
            new Station(252, "Yamuna Bank", "Blue"),
            new Station(253, "Laxmi Nagar", "Blue"),
            new Station(254, "Nirman Vihar", "Blue"),
            new Station(255, "Preet Vihar", "Blue"),
            new Station(256, "Karkar Duma", "Blue"),
            new Station(257, "Anand Vihar", "Blue"),
            new Station(258, "Kaushambi", "Blue"),
            new Station(259, "Vaishali", "Blue"),
            new Station(260, "Ashok Park Main", "Green"),
            new Station(261, "Satguru Ram Singh Marg", "Green"),
            new Station(262, "Kirti Nagar", "Green"),
            new Station(263, "Noida Sector 51", "Aqua"),
            new Station(264, "Noida Sector 50", "Aqua"),
            new Station(265, "Noida Sector 76", "Aqua"),
            new Station(266, "Noida Sector 101", "Aqua"),
            new Station(267, "Noida Sector 81", "Aqua"),
            new Station(268, "NSEZ Noida", "Aqua"),
            new Station(269, "Noida Sector 83", "Aqua"),
            new Station(270, "Noida Sector 137", "Aqua"),
            new Station(271, "Noida Sector 142", "Aqua"),
            new Station(272, "Noida Sector 143", "Aqua"),
            new Station(273, "Noida Sector 144", "Aqua"),
            new Station(274, "Noida Sector 145", "Aqua"),
            new Station(275, "Noida Sector 146", "Aqua"),
            new Station(276, "Noida Sector 147", "Aqua"),
            new Station(277, "Noida Sector 148", "Aqua"),
            new Station(278, "Knowledge Park II", "Aqua"),
            new Station(279, "Pari Chowk Greater Noida", "Aqua"),
            new Station(280, "Alpha 1 Greater Noida", "Aqua"),
            new Station(281, "Delta 1 Greater Noida", "Aqua"),
            new Station(282, "GNIDA Office", "Aqua"),
            new Station(283, "Depot Greater Noida", "Aqua"),
            new Station(284, "Dwarka", "Gray"),
            new Station(285, "Nangli", "Gray"),
            new Station(286, "Najafgarh", "Gray")
    ));

    public static ArrayList<Station> getStations() {
        return stations;
    }

    public String get(String str) {
        String[] a = str.split("Conn:");
        return a[a.length-1];
    }
    public void doit() {
        WebDriver driver = new ChromeDriver();
        driver.get("https://delhimetrorail.info/delhi-metro-stations");

        ArrayList<WebElement> as = (ArrayList<WebElement>) driver.findElements(By.xpath("//section[@id='GrayLine']//td[@class='left']"));
        ArrayList<String> lines = new ArrayList<>();
        lines.add("Red");
        int id = 284;
        for (WebElement a : as) {
            String stationName = a.findElement(By.tagName("a")).getText();
            String line = "";
            if (a.getText().contains("Conn:")) {
               line = get(a.getText()).trim();
            }
            System.out.println("new Station(" + id++ + ", \"" + stationName + "\", " + "\"Gray\"" + "),");
       }

        driver.get("https://www.google.com/");
        driver.findElement(By.xpath("//textarea[@title='Search']")).sendKeys("sahil");
    }
}
